/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./../components/Aside/index.vue')['default']
    BaseMap: typeof import('./../components/BaseMap/index.vue')['default']
    ColumnsSelect: typeof import('./../components/ColumnsSelect/index.vue')['default']
    DictTag: typeof import('./../components/DictTag/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"]
    ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"]
    ElButton: typeof import("element-plus/es")["ElButton"]
    ElCard: typeof import("element-plus/es")["ElCard"]
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import("element-plus/es")["ElDatePicker"]
    ElDialog: typeof import("element-plus/es")["ElDialog"]
    ElForm: typeof import("element-plus/es")["ElForm"]
    ElFormItem: typeof import("element-plus/es")["ElFormItem"]
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import("element-plus/es")["ElInput"]
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import("element-plus/es")["ElPagination"]
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import("element-plus/es")["ElTable"]
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"]
    ElUpload: typeof import("element-plus/es")["ElUpload"]
    LGeojson: typeof import('@/vue-leaflet')['LGeojson']
    LImgLaryer: typeof import('./../components/LImgLaryer/index.vue')['default']
    LMap: typeof import('@/vue-leaflet')['LMap']
    LTileLayer: typeof import('@/vue-leaflet')['LTileLayer']
    MapRadar: typeof import('./../components/MapRadar/MapRadar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./../components/Upload/upload.vue')['default']
    ZEcharts: typeof import('./../components/ZEcharts/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import("element-plus/es")["ElLoadingDirective"]
  }
}
